artefacts_root: artefacts


data_ingestion:
  root_dir: artefacts/data_ingestion
  source_url: https://drive.google.com/file/d/18RUmxY6OHU9w-V_fc0xSoUeDUrMypws5/view?usp=sharing
  local_data_file: artefacts/data_ingestion/data.zip
  unzip_dir: artefacts/data_ingestion


prepare_base_model:
  root_dir: artefacts/prepare_base_model
  base_model_path: artefacts/prepare_base_model/base_model.h5
  updated_base_model_path: artefacts/prepare_base_model/base_model_updated.h5