artefacts_root: artefacts


data_ingestion:
  root_dir: artefacts/data_ingestion
  source_url: https://drive.google.com/file/d/18RUmxY6OHU9w-V_fc0xSoUeDUrMypws5/view?usp=sharing
  local_data_file: artefacts/data_ingestion/data.zip
  unzip_dir: artefacts/data_ingestion